# My first Python notebook

### Homework

## Strings

1. Assign the value of 80 to the variable `d`.

In [2]:
d = 80

2. Using the variable `d`, write one line of code where the output after execution is "Around the World in 80 Days" (hint: there are several ways to achieve this result).

In [4]:
print(f"Around the world in {d} days")

Around the world in 80 days
Around the world in 80 days
Around the world in 80 days

In [6]:
print("Around the world in " + str(d) + " days")

Around the world in 80 days

In [7]:
print("Around the world in %d days" % d)

Around the world in 80 days

In [9]:
print(" ".join(["Around the world in", str(d), "days"]))

Around the world in 80 days

3. Write a string that says "It's hot, don't you think?"

In [12]:
"It's hot, don't you think?"

"It's hot, don't you think?"

4. Fix the cell below so that it becomes a string.

In [11]:
"Don't be shy!"

"Don't be shy!"

5. Produce an output equal to `Click "OK"`.

In [10]:
print("Click \"OK\"")

Click "OK"

## Numbers and Boolean Operators

1. Create a variable equal to "True" and call it `b`. Then check its type.

In [14]:
b = True

In [15]:
print(type(b))

<class 'bool'>

2. Create a variable equal to 42 and call it `x`. Then check its type

In [17]:
x = 42

In [18]:
print(type(x))

<class 'int'>

3. Check the type of the value 3.14. Then turn it into an integer and write the result as a comment.

In [19]:
print(type(3.14))

<class 'float'>

In [20]:
print(type(int(3.14)))

<class 'int'>

4. Verify that 25 is smaller than 30. Then verify that 10 multiplied by 3 is less than or equal to 10 to the power of 3.

In [21]:
print(25 < 30)

True

In [22]:
print(10 * 3 <= 10 ** 3)

True

5. Verify that 100 is equal to 10 square. Then verify that 42 is not equal to 314.

In [23]:
print( 100 == 10 ** 2)

True

In [24]:
print(42 != 314)

True

6. Using the operators `True`, `False`, `not` and `is` exactly once, generate a `True` output.

In [25]:
print(True and False is not True)

True

## Arithmetic operators

1. Add 34 and 26, from the result subtract 50. Then assign this operation to a variable and call it `y`.

In [26]:
result = 34 + 26
result -= 50
y = result

In [27]:
print(y)

10

2. Divide 60 by the sum of `y` and 5.

In [28]:
print(60 / (y + 5))

4.0

3. Divide `y` by 4. Then obtain the **remainder** of the division.

In [30]:
y = y % 4

In [31]:
print(y)

2.5

4. Raise 35 to the power of 4.

In [32]:
print(35 ** 4)

1500625

5. Take the square root of 1764.

In [33]:
print(1764 ** 0.5)

42.0

## Variables & assignment

1. Create a variable, call it `z` and assign it a value of 10. Then show the value of the variable on the screen.

In [34]:
z = 10

In [35]:
print(z)

10

2. Using one line of code, create three new variables: `one`, `two` and `three`, that are equal to 10, 20 and 30 respectively.

In [36]:
one, two, three = 10, 20, 30

3. Tell Python to output the sum of the three variables.

In [40]:
print(one + two + three)

60

4. Using the three variables from above, output the value "102030" as a string.

In [41]:
print(f"{one}{two}{three}")

102030

5. Assign the value of 10 to a variable `w` and, in the same cell, print `w` on the screen. Then multiply `w` by 10.

In [43]:
w = 10
print(w)

10

In [44]:
w *= 10

6. Now, assign 30 to the variable `w`. Then calculate `w` + 10. Notice how the value of `w` changes and is always the last one you have assigned.

In [45]:
w = 30

In [46]:
print(w+10)

40

## Indexing elements

1. Using string indexing, extract the letter 'B' from "Boolean".

In [47]:
print("Boolean"[0])

B

2. Using string indexing, extract the substring "lean" from "Boolean".

In [49]:
print("Boolean"[3:])

lean

3. Using string indexing, extract the exclamation mark from "Hello World!".

In [50]:
print("Hello World!"[-1])

!

4. Using string indexing, extract the substring "UAE" from the following text: "Israel signs first Arab free trade agreement with UAE."

In [51]:
print("Israel signs first Arab free trade agreement with UAE."[-4:-1])

UAE